### PR TITLE
Usg 0.9

### PR DESCRIPTION
**Pull request by veritekemp**

### CODE REVIEW

**Comment by robertfisk** [comment]
Hi veritekemp,

Both the 0.9 and 1.0 branches have the same features. I am keeping them in sync by cherry-picking all relevant commits between branches. This might not be best practice but it works for me.

The only differences between the 0.9 and 1.0 branches are required by the change in MCU (STM32F405 / 407 to the STM32F401), different crystal frequencies, and different PCB layout. Everything else is the same. Is there a particular problem you are trying to solve here?

**Comment by veritekemp** [comment]
Hi Robert,

Thanks for the note.

I really like what you have started.

I’ve built the .9 and trying to program it with a JTAG.  Wanting to experiment to see how it performs for me against different attacks.  I am at the point of programming the processors and need the code.

**Comment by robertfisk** [comment]
Thanks for your interest, and good to hear you have built up a v0.9 unit yourself. All you need to do is checkout the USG_0.9 branch. All the latest features are in there, no need for any merges!

**Comment by veritekemp** [comment]
Thank you Robert,

I’ve not worked with the arm processor before or with github.  Having trouble downloading files.  Any suggestions?

Jim

**Comment by robertfisk** [comment]
(This conversation has been moved to email...)

**Pull request closed without merging**
